### ISSUE TITLE
Sharing page error: Module 'extra' not found

### ISSUE THREAD

**Issue by droumis** [awesome-panel/awesome-panel#77]
### Description

Opening https://awesome-panel.org/sharing? I encountered the error shown below.

![image](https://user-images.githubusercontent.com/6613202/203296903-6202ceb9-386c-4db8-9657-271e6b3fb8d5.png)

### Reproduction steps

Unfortunately, I haven't been able to reproduce it yet. Feel free to close this issue, but I just wanted to report it so that you were aware.

### Logs

```bash
dist.min.js:70 loaders.gl: The __VERSION__ variable is not injected using babel plugin. Latest unstable workers would be fetched from the CDN.
../worker-utils/src/lib/env-utils/version.ts @ dist.min.js:70
bokeh.min.js?v=3c61e952b808bb7e346ce828a565a5f23aaf7708d034fa9d0906403813355d45bb4e8d8b0b23a93f032c76831d4f0221846f28699c7f5147caa62e0d31668314:184 [bokeh] setting log level to: 'info'
react-dom.development.js:25129 Download the React DevTools for a better development experience: https://fb.me/react-devtools
babel.min.js:24 You are using the in-browser Babel transformer. Be sure to precompile your scripts for production - https://babeljs.io/docs/setup/
u @ babel.min.js:24
react.development.js:1641 Warning: Failed prop type: maxWidth not Number
    in i (created by ReactGridLayout)
    in ReactGridLayout (created by i)
    in i (created by u)
    in u (created by ResponsiveGrid)
    in ResponsiveGrid
printWarning$1 @ react.development.js:1641
react.development.js:1641 Warning: Failed prop type: maxHeight not Number
    in i (created by ReactGridLayout)
    in ReactGridLayout (created by i)
    in i (created by u)
    in u (created by ResponsiveGrid)
    in ResponsiveGrid
printWarning$1 @ react.development.js:1641
bokeh.min.js?v=3c61e952b808bb7e346ce828a565a5f23aaf7708d034fa9d0906403813355d45bb4e8d8b0b23a93f032c76831d4f0221846f28699c7f5147caa62e0d31668314:587 [bokeh] Websocket connection 0 is now open
panel.min.js?v=43806f317ec11e3f7908f75455e18400ad8aea9cf3f8c935f83e80e59910a76a:101 Unrecognized feature: 'layout-animations'.
render @ panel.min.js?v=43806f317ec11e3f7908f75455e18400ad8aea9cf3f8c935f83e80e59910a76a:101
panel.min.js?v=43806f317ec11e3f7908f75455e18400ad8aea9cf3f8c935f83e80e59910a76a:101 Unrecognized feature: 'legacy-image-formats'.
render @ panel.min.js?v=43806f317ec11e3f7908f75455e18400ad8aea9cf3f8c935f83e80e59910a76a:101
panel.min.js?v=43806f317ec11e3f7908f75455e18400ad8aea9cf3f8c935f83e80e59910a76a:101 Unrecognized feature: 'oversized-images'.
render @ panel.min.js?v=43806f317ec11e3f7908f75455e18400ad8aea9cf3f8c935f83e80e59910a76a:101
panel.min.js?v=43806f317ec11e3f7908f75455e18400ad8aea9cf3f8c935f83e80e59910a76a:101 Unrecognized feature: 'speaker-selection'.
render @ panel.min.js?v=43806f317ec11e3f7908f75455e18400ad8aea9cf3f8c935f83e80e59910a76a:101
panel.min.js?v=43806f317ec11e3f7908f75455e18400ad8aea9cf3f8c935f83e80e59910a76a:101 Unrecognized feature: 'unoptimized-images'.
render @ panel.min.js?v=43806f317ec11e3f7908f75455e18400ad8aea9cf3f8c935f83e80e59910a76a:101
panel.min.js?v=43806f317ec11e3f7908f75455e18400ad8aea9cf3f8c935f83e80e59910a76a:101 Unrecognized feature: 'unsized-media'.
render @ panel.min.js?v=43806f317ec11e3f7908f75455e18400ad8aea9cf3f8c935f83e80e59910a76a:101
panel.min.js?v=43806f317ec11e3f7908f75455e18400ad8aea9cf3f8c935f83e80e59910a76a:101 Unrecognized feature: 'web-share'.
render @ panel.min.js?v=43806f317ec11e3f7908f75455e18400ad8aea9cf3f8c935f83e80e59910a76a:101
bokeh.min.js?v=3c61e952b808bb7e346ce828a565a5f23aaf7708d034fa9d0906403813355d45bb4e8d8b0b23a93f032c76831d4f0221846f28699c7f5147caa62e0d31668314:165 [bokeh] document idle at 52 ms
bokeh.min.js?v=3c61e952b808bb7e346ce828a565a5f23aaf7708d034fa9d0906403813355d45bb4e8d8b0b23a93f032c76831d4f0221846f28699c7f5147caa62e0d31668314:163 Bokeh items were rendered successfully
cdnjs.cloudflare.com/ajax/libs/ace/1.4.11/mode-txt.js:1          Failed to load resource: the server responded with a status of 404 ()
bokeh-2.4.3.min.js:184 [bokeh] setting log level to: 'info'
bokeh-2.4.3.min.js:165 [bokeh] document idle at 8 ms
app.js:12 Loading pyodide!
pyodide.asm.js:10 Loading distutils
pyodide.asm.js:10 Loaded distutils
pyodide.asm.js:10 Python initialization complete
app.js:16 Loaded!
pyodide.asm.js:10 distutils already loaded from default channel
pyodide.asm.js:10 Loading micropip, pyparsing, packaging
pyodide.asm.js:10 Loaded pyparsing, packaging, micropip
pyodide.asm.js:10 Loading typing-extensions, pyyaml, pillow, jinja2, markupsafe, numpy
pyodide.asm.js:10 Loaded typing-extensions, markupsafe, jinja2, pyyaml, pillow, numpy
pyodide.asm.js:10 distutils already loaded from default channel
pyodide.asm.js:10 pyparsing already loaded from default channel
pyodide.asm.js:10 packaging already loaded from default channel
pyodide.asm.js:10 Loading setuptools, tqdm, bleach, webencodings, six, certifi
pyodide.asm.js:10 Loaded webencodings, six, tqdm, certifi, bleach, setuptools
app.js:40 Packages loaded!
pyodide.asm.js:10 Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 506, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 359, in run_async
    await coroutine
  File "<exec>", line 44, in <module>
  File "/lib/python3.10/site-packages/panel/io/pyodide.py", line 400, in write_doc
    template.server_doc(title=template.title, location=True, doc=pydoc)
  File "/lib/python3.10/site-packages/panel/template/base.py", line 348, in server_doc
    return self._init_doc(doc, title=title, location=location)
  File "/lib/python3.10/site-packages/panel/template/base.py", line 575, in _init_doc
    document = super()._init_doc(doc, comm, title, notebook, location)
  File "/lib/python3.10/site-packages/panel/template/base.py", line 200, in _init_doc
    model = obj.get_root(document, comm, preprocess=False)
  File "/lib/python3.10/site-packages/panel/viewable.py", line 559, in get_root
    root = self._get_model(doc, comm=comm)
  File "/lib/python3.10/site-packages/panel/layout/base.py", line 146, in _get_model
    objects = self._get_objects(model, [], doc, root, comm)
  File "/lib/python3.10/site-packages/panel/layout/base.py", line 131, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "/lib/python3.10/site-packages/panel/pane/markup.py", line 53, in _get_model
    model = self._bokeh_model(**self._get_properties())
  File "/lib/python3.10/site-packages/panel/pane/markup.py", line 359, in _get_properties
    html = markdown.markdown(data, extensions=self.extensions,
  File "/lib/python3.10/site-packages/markdown/core.py", line 386, in markdown
    md = Markdown(**kwargs)
  File "/lib/python3.10/site-packages/markdown/core.py", line 96, in __init__
    self.registerExtensions(extensions=kwargs.get('extensions', []),
  File "/lib/python3.10/site-packages/markdown/core.py", line 123, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "/lib/python3.10/site-packages/markdown/core.py", line 162, in build_extension
    module = importlib.import_module(ext_name)
  File "/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'extra'

    at new_error (pyodide.asm.js:10:218123)
    at pyodide.asm.wasm:0xdef7c
    at pyodide.asm.wasm:0xe37ae
    at method_call_trampoline (pyodide.asm.js:10:218037)
    at pyodide.asm.wasm:0x126317
    at pyodide.asm.wasm:0x1f6f2e
    at pyodide.asm.wasm:0x161a32
    at pyodide.asm.wasm:0x126827
    at pyodide.asm.wasm:0x126921
    at pyodide.asm.wasm:0x1269c4
    at pyodide.asm.wasm:0x1e0697
    at pyodide.asm.wasm:0x1da6a5
    at pyodide.asm.wasm:0x126a07
    at pyodide.asm.wasm:0x1e248c
    at pyodide.asm.wasm:0x1e00d9
    at pyodide.asm.wasm:0x1da6a5
    at pyodide.asm.wasm:0x126a07
    at pyodide.asm.wasm:0xe347a
    at Module.callPyObjectKwargs (pyodide.asm.js:10:119064)
    at Module.callPyObject (pyodide.asm.js:10:119442)
    at wrapper (pyodide.asm.js:10:183746)
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for https://awesome-panel.org/static/extensions/panel/bundled/vegaplot/vega.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://awesome-panel.org/static/extensions/panel/bundled/vegaplot/vega-embed.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://awesome-panel.org/static/extensions/panel/bundled/vegaplot/vega-lite.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by MarcSkovMadsen** [comment]
My understanding is that its `panel convert` that has the issue. I've seen something similar for `base64`. But Philipp could not reproduce it.
