### ISSUE TITLE
Sharing Page Unconvertable App

### ISSUE THREAD

**Issue by firobeid** [awesome-panel/awesome-panel#79]
### Description

Failed to convert. Make sure you only import packages already installed on the
server.

Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/bokeh/application/handlers/code_runner.py", line 231, in run
exec(self._code, module.__dict__)
File "/tmp/tmpx7l4lfpo/source/app.py", line 7, in
from github import Github
ModuleNotFoundError: No module named 'github'

### Reproduction steps

Failed to convert. Make sure you only import packages already installed on the
server.

Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/bokeh/application/handlers/code_runner.py", line 231, in run
exec(self._code, module.__dict__)
File "/tmp/tmpx7l4lfpo/source/app.py", line 7, in
from github import Github
ModuleNotFoundError: No module named 'github'

### Requirements

```bash
pip install PyGithub
```

### Code

```python3
from github import Github
repo_name = 'firobeid/TimeSeriesCompetitionTracker'
# First create a Github instance:

# using an access token
g = Github("xxxx")

# Github Enterprise with custom hostname
# g = Github(base_url="https://api.github.com/firobeid/firobeid.github.io", login_or_token="access_token")
# https://api.github.com/firobeid/firobeid.github.io

# Then play with your Github objects:
for repo in g.get_user().get_repos():
    print(repo.name)
```

### Additional Context

Package dosent have wasm or none wheel

**Comment by MarcSkovMadsen** [comment]
Hi @firobeid 

The issue with `PyGithub` is that it depends on other python packages that don't work (yet) with pyodide. In the browser console of a `panel convert`ed app i see

```bash
ValueError: Can't find a pure Python 3 wheel for 'aiohttp==3.8.1'.
See: https://pyodide.org/en/stable/usage/faq.html#micropip-can-t-find-a-pure-python-wheel
```

## Reproducible Example

```python
from github import Github
import pandas as pd
import panel as pn

pn.extension(sizing_mode="stretch_width")

token = pn.widgets.PasswordInput(name='Github Token', placeholder='Enter your Github Token here...', max_width=500)

@pn.depends(token)
def get_repos(token):
    if not token:
        return "No token provided"
    g = Github(token)
    repositories = g.get_user().get_repos()
    return pd.DataFrame({
        "repository": [repository.name for repository in repositories]
    })

pn.Column(
    token, pn.panel(get_repos, loading_indicator=True)
).servable()
```

**Comment by MarcSkovMadsen** [comment]
I've made a request for supporting pynacl here https://github.com/pyodide/pyodide/issues/3327.

**Comment by firobeid** [comment]
Thank you Marc! I will male sure to request there directly for future packages.
